angka1 = input("Masukan Angka Pertama : ")
angka2 = input("Masukan Angka Kedua : ")
penjumlahan = int(angka1)+int(angka2)
pengurangan  = int(angka1)-int(angka2)
perkalian  = int(angka1)*int(angka2)
pembagian  = int(angka1)/int(angka2)
print("Hasil Penjumlahan adalah :", penjumlahan)
print("Hasil Pengurangan adalah :", pengurangan)
print("Hasil Perkalian adalah :", perkalian)
print("Hasil Pembagian adalah :", pembagian)